name: EnchantmentSolution
version: 2.4.1
main: org.ctp.enchantmentsolution.EnchantmentSolution
api-version: 1.13
depend: [CrashAPI]
softdepend: [mcMMO, Jobs, VeinMiner, AuctionHouse, MMOLib, MMOItems, Quests, Vault]
commands:
  enchantmentsolution:
    aliases: [es]
    description: All commands for EnchantmentSolution
    usage: /enchantmentsolution
  enchant:
    aliases: [customenchant]
    description: Add enchantments to items.
    usage: /enchant <enchant_name> [level]
  enchantunsafe:
    aliases: [customenchantunsafe]
    description: Displays commands
    usage: /enchantunsafe <enchant_name> [level]
  info:
    aliases: [enchantinfo]
    description: Gives player information on an enchantment.
    usage: /info [enchant_name]
  removeenchant:
    aliases: [eremove]
    description: Remove enchantment from item.
    usage: /removeenchant <enchant_name>
  esreload:
    description: Reload config files
    usage: /esreload
  esconfig:
    description: Edit config files
    usage: /esconfig
  esreset:
    description: Reset all custom inventories
    usage: /esreset
  esdebug:
    description: Generates a debug file for debugging and testing
    usage: /esdebug
  escalc:
    description: Calculate the levels that would be possible with certain enchantabilities
    usage: /escalc
  esbook:
    aliases: [book]
    description: Gives the player a book with specified enchantment; use RandomEnchant or RandomMultiEnchant for random enchantments
    usage: /esbook
  esanvil:
    aliases: [anvil]
    description: Opens the ES custom inventory anvil
    usage: /esanvil
  esgrindstone:
    aliases: [grindstone]
    description: Opens the ES custom inventory grindstone
    usage: /esgrindstone
  configlore:
    description: Gets the hidden chat color value for strings to be used in ES enchantments
    usage: /configlore
  esrpg:
    description: Gets the ES RPG information if the RPG mode is enabled
    usage: /esrpg
  eshelp:
    description: Gets a list of commands and their usages
    usage: /eshelp
  esfix:
    description: Fixes items to make their enchantments work
    usage: /esfix
  rpgstats:
    description: Gets a player's stats from ESRPG
    usage: /rpgstats
  rpgtop:
    description: Gets a leaderboard for ESRPG players
    usage: /rpgtop
  rpgedit:
    description: Edits a player's ESRPG information
    usage: /rpgedit
  estest:
    description: Test items for plugin info
    usage: /estest [item]
permissions:
  enchantmentsolution.permissions.ignore: 
    description: Gives access to all enchantment permissions.
    default: false
  enchantmentsolution.abilities.has-external-flight:
    description: Enables use of external /fly commands without interference from FrequentFlyer
    default: false
  enchantmentsolution.abilities.player-skulls:
    description: Enables dropping player's skulls with Beheading
    default: true
  enchantmentsolution.abilities.custom-skulls:
    description: Enables dropping custom skulls with Beheading
    default: true
  enchantmentsolution.enchantments.rpg.all: 
    description: Gives access to every enchantment through ESRPG.
    default: op
  enchantmentsolution.enchantments.lower-levels:
    description: Only allow the player to have enchantments and enchantment levels that match their permission levels
    default: false
  enchantmentsolution.anvil.demigod:
    description: Allows players to repair items with enchantments they cannot combine
    default: false
  enchantmentsolution.anvil.demigod-books:
    description: Allows players to add levels from enchanted books to items even if they cannot combine the levels
    default: false
  enchantmentsolution.anvil.god:
    description: Allows players to combine items higher than their max levels
    default: false
  enchantmentsolution.anvil.rename:
    description: Allows players to rename their items with the custom GUI
    default: op
  enchantmentsolution.command.calculator:
    description: Allows players to use the /es calc command
    default: op
  enchantmentsolution.command.edit: 
    description: Gives access to the /es config command. 
    default: op
  enchantmentsolution.command.enchant: 
    description: Gives access to the /es enchant command. 
    default: op
  enchantmentsolution.command.enchant.others: 
    description: Gives access to the /es enchant command for use on other people. 
    default: op
  enchantmentsolution.command.reload: 
    description: Gives access to the /es reload command. 
    default: op
  enchantmentsolution.command.enchantremove: 
    description: Gives access to the /es removeenchant command. 
    default: op
  enchantmentsolution.command.enchantremove.others: 
    description: Gives access to the /es removeenchant command for use on other people. 
    default: op
  enchantmentsolution.command.reset: 
    description: Gives access to the /es reset command. 
    default: op
  enchantmentsolution.command.enchantunsafe: 
    description: Gives access to the /es enchantunsafe command.
    default: op
  enchantmentsolution.command.enchantunsafe.others: 
    description: Gives access to the /es enchantunsafe command for use on other people. 
    default: op
  enchantmentsolution.command.debug:
    description: Allows players to use the /es debug command
    default: op
  enchantmentsolution.command.book:
    description: Allows players to use the /es book command
    default: op
  enchantmentsolution.command.anvil:
    description: Allows players to use the /es anvil command
    default: op
  enchantmentsolution.command.grindstone:
    description: Allows players to use the /es grindstone command
    default: op
  enchantmentsolution.command.configlore:
    description: Allows players to use the /es lore command
    default: op
  enchantmentsolution.command.help:
    description: Allows players to use the /es help command
    default: true
  enchantmentsolution.command.info:
    description: Allows players to use the /es info command
    default: true
  enchantmentsolution.command.fix:
    description: Allows players to use the /es fix command
    default: op
  enchantmentsolution.command.fix.others:
    description: Allows players to use the /es fix command on others
    default: op
  enchantmentsolution.command.rpg:
    description: Allows players to use the /es rpg command
    default: op
  enchantmentsolution.command.rpgstats:
    description: Allows players to use the /es rpgstats command
    default: op
  enchantmentsolution.command.rpgstats.others:
    description: Allows players to use the /es rpgstats command on others
    default: op
  enchantmentsolution.command.rpgtop:
    description: Allows players to use the /es rpgtop command
    default: op
  enchantmentsolution.command.rpgedit:
    description: Allows players to use the /es rpgedit command
    default: op
  enchantmentsolution.command.test:
    description: Allows players to use the /es test command
    default: op