name: EnchantmentSolution
version: 2.1.9
main: org.ctp.enchantmentsolution.EnchantmentSolution
api-version: 1.13
softdepend: [mcMMO, Jobs, VeinMiner]
commands:
  enchant:
    aliases: [es,customenchant]
    description: Add enchantments to items.
    usage: /enchant <enchant_name> [level]
  enchantunsafe:
    aliases: [esu,customenchantunsafe]
    description: Displays commands
    usage: /enchantunsafe <enchant_name> [level]
  info:
    aliases: [einfo,enchantinfo]
    description: Gives player information on an enchantment.
    usage: /info [enchant_name]
  removeenchant:
    aliases: [esr,eremove]
    description: Remove enchantment from item.
    usage: /removeenchant <enchant_name>
  esreload:
    description: Reload config files
    usage: /esreload
  esconfig:
    description: Edit config files
    usage: /esconfig
  esreset:
    description: Reset all custom inventories
    usage: /esreset
  esdebug:
    description: Generates a debug file for debugging and testing
    usage: /esdebug
permissions:
  enchantmentsolution.command.edit: 
    description: Gives access to the /esconfig command. 
    default: op
  enchantmentsolution.command.enchant: 
    description: Gives access to the /enchant command. 
    default: op
  enchantmentsolution.command.reload: 
    description: Gives access to the /esreload command. 
    default: op
  enchantmentsolution.command.enchantremove: 
    description: Gives access to the /removeenchant command. 
    default: op
  enchantmentsolution.command.reset: 
    description: Gives access to the /esreset command. 
    default: op
  enchantmentsolution.command.enchantunsafe: 
    description: Gives access to the /enchantunsafe command.
    default: op
  enchantmentsolution.enable-flight:
    description: Enables use of external /fly commands without interference from FrequentFlyer
    default: false
  enchantmentsolution.permissions.ignore: 
    description: Gives access to all enchantment permissions.
    default: false
  enchantmentsolution.demigod-anvil:
    description: Allows players to repair items with enchantments they cannot combine
    default: false
  enchantmentsolution.demigod-books:
    description: Allows players to add levels from enchanted books to items even if they cannot combine the levels
    default: false
  enchantmentsolution.god-anvil:
    description: Allows players to combine items higher than their max levels
    default: false
  enchantmentsolution.debug:
    description: Allows players to use the /esdebug command
    default: op